spring.application.name=gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

server.port=8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=00d23b30-8bd5-4cfa-935c-9305be24d5f7
