# Config minima local: nome da aplicacao (usado para buscar
# "clientes-service.properties" no config-server) e o endereco do config-server.
# O restante das configuracoes (porta, datasource, eureka...) vem do
# repositorio Git via config-server, em config-repo/clientes-service.properties.
spring.application.name=clientes-service
#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:http://config-server:8888
